apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: adia
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: lpsouza/adia-app:latest
          resources:
            limits:
              cpu: "100m"
              memory: "256Mi"
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app
            - secretRef:
                name: app
